# Generated by Django 5.1.3 on 2024-11-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["date_time", "status"],
                "permissions": [
                    ("can_view_mailing", "Can view mailing"),
                    ("can_block_user", "Can block user"),
                    ("can_disable_mailing", "Can disable mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
